version: "3.7"
services:
  client:
    build:
      context: .
      target: dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_BACKEND: $REACT_APP_LOCAL_BACKEND
      REACT_APP_AUTH_DOMAIN: $REACT_APP_AUTH_DOMAIN
      REACT_APP_AUTH_AUDIENCE: $REACT_APP_AUTH_AUDIENCE
      REACT_APP_AUTH_CLIENT_ID: $REACT_APP_AUTH_CLIENT_ID
    restart: always
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    volumes:
      - .:/client/app
      - /client/app/node_modules
    tty: true
    stdin_open: true
