version: "3.7"
services:
  client:
    build:
      context: .
      target: dev
    environment:
      PORT: $PORT
      HTTPS: "true"
      REACT_APP__FRESHBOOKS_CLIENT_ID: $REACT_APP_FRESHBOOKS_CLIENT_ID
      REACT_APP__FRESHBOOKS_CLIENT_SECRET: $REACT_APP_FRESHBOOKS_CLIENT_SECRET
      REACT_APP__AWS_COGNITO_IDENTITY: $REACT_APP__AWS_COGNITO_IDENTITY
      REACT_APP__AWS_S3_BUCKET: $REACT_APP__AWS_S3_BUCKET
      REACT_APP__AWS_S3_BUCKET_REGION: $REACT_APP__AWS_REGION
      REACT_APP__AUTH0_DOMAIN: $REACT_APP__AUTH0_DOMAIN
      REACT_APP__AUTH0_AUDIENCE: $REACT_APP__AUTH0_AUDIENCE
      REACT_APP__AUTH0_CLIENT_ID: $REACT_APP__AUTH0_CLIENT_ID
      REACT_APP__BACKEND: $REACT_APP__BACKEND
    restart: always
    ports:
      - $PORT:$PORT
    volumes:
      - .:/client/app
      - /client/app/node_modules
    tty: true
    stdin_open: true
