name: Client Single Page Application

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: client single page application
        run: |
          docker build . --tag ghcr.io/${{ github.repository_owner }}/spa-client:latest
          docker push ghcr.io/${{ github.repository_owner }}/spa-client:latest
